YACC = bison
FLEX = flex
GCC = gcc
RM = rm


TARGET = ag
SOURCE = Makefile scan.l gram.y

YFLAGS = -d 
GCCFLAGS = -Wall -Wextra -pedantic -g 
LDFLAGS = -lfl

all: $(TARGET)

$(TARGET): 



clean: 
	rm -f $(TARGET)
